# Name: Lindsey Reynolds
# Date: 03/24/20
# Title: Lab 3 Makefile

# declare variables
CC=gcc
CFLAGS=-o

all: step1 step2 step3

step1: lab3_1.c
	$(CC) lab3_1.c $(CFLAGS) output1

step2: lab3_2.c
	$(CC) lab3_2.c $(CFLAGS) output2

step3: lab3_3.c
	$(CC) lab3_3.c $(CFLAGS) output3

clean:
	rm output1 output2 output3